name: CI Basic Workflow
on: [push, pull_request]

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v1
        with:
          files: '**/*.yml'
